const GAMES = [
  { id:"ovo", name:"OvO", desc:"Fast parkour platformer", emoji:"⬜", rating:"97%", players:"1.3K", hot:true, isNew:false, url:"https://ubg98.github.io/OvO/" },
  { id:"run3", name:"Run 3", desc:"Sprint through space tunnels", emoji:"🏃", rating:"95%", players:"2.1K", hot:true, isNew:false, url:"https://classroom6x.github.io/run-3/" },
  { id:"slope", name:"Slope", desc:"Roll a neon ball, don't fall!", emoji:"🎳", rating:"94%", players:"1.9K", hot:true, isNew:false, url:"https://ubg98.github.io/Slope/" },
  { id:"drifthunters", name:"Drift Hunters", desc:"Drift cars on epic tracks", emoji:"🚗", rating:"92%", players:"1.4K", hot:false, isNew:false, url:"https://ubg98.github.io/Drift-Hunters/" },
  { id:"subway", name:"Subway Surfers", desc:"Run from the inspector!", emoji:"🚇", rating:"93%", players:"2.5K", hot:true, isNew:false, url:"https://ubg98.github.io/Subway-Surfers/" },
  { id:"motox3m", name:"Moto X3M", desc:"Crazy motorcycle stunts", emoji:"🏍️", rating:"91%", players:"1.1K", hot:false, isNew:false, url:"https://ubg98.github.io/Moto-X3M/" },
  { id:"cookieclicker", name:"Cookie Clicker", desc:"Click cookies, build empire", emoji:"🍪", rating:"89%", players:"3.2K", hot:false, isNew:false, url:"https://orteil.dashnet.org/cookieclicker/" },
  { id:"2048", name:"2048", desc:"Slide tiles to reach 2048", emoji:"🔢", rating:"88%", players:"900", hot:false, isNew:false, url:"https://play2048.co/" },
  { id:"geometrydash", name:"Geometry Dash", desc:"Jump to the beat!", emoji:"🔷", rating:"96%", players:"1.8K", hot:true, isNew:false, url:"https://ubg98.github.io/Geometry-Dash/" },
  { id:"basketball", name:"Basketball Stars", desc:"1v1 basketball action", emoji:"🏀", rating:"90%", players:"1.2K", hot:false, isNew:false, url:"https://ubg98.github.io/Basketball-Stars/" },
  { id:"retrobowl", name:"Retro Bowl", desc:"Manage your NFL team", emoji:"🏈", rating:"95%", players:"1.6K", hot:false, isNew:true, url:"https://ubg98.github.io/Retro-Bowl/" },
  { id:"snowrider", name:"Snow Rider 3D", desc:"Sled down snowy hills", emoji:"🛷", rating:"91%", players:"1.0K", hot:false, isNew:true, url:"https://ubg98.github.io/Snow-Rider-3D/" },
  { id:"drivemad", name:"Drive Mad", desc:"Crazy physics car game", emoji:"🚙", rating:"93%", players:"1.3K", hot:true, isNew:false, url:"https://ubg98.github.io/Drive-Mad/" },
  { id:"monkeymart", name:"Monkey Mart", desc:"Run a supermarket as a monkey", emoji:"🐵", rating:"92%", players:"800", hot:false, isNew:true, url:"https://ubg98.github.io/Monkey-Mart/" },
  { id:"clusterrush", name:"Cluster Rush", desc:"Jump across speeding trucks", emoji:"🚛", rating:"94%", players:"980", hot:false, isNew:true, url:"https://ubg98.github.io/Cluster-Rush/" },
  { id:"happywheels", name:"Happy Wheels", desc:"Ragdoll physics chaos", emoji:"🛞", rating:"88%", players:"1.1K", hot:false, isNew:false, url:"https://ubg98.github.io/Happy-Wheels/" },
  { id:"idlebreakout", name:"Idle Breakout", desc:"Idle clicker breakout", emoji:"🧱", rating:"87%", players:"600", hot:false, isNew:false, url:"https://ubg98.github.io/Idle-Breakout/" },
  { id:"paperiov2", name:"Paper.io 2", desc:"Claim territory, cut rivals", emoji:"📄", rating:"89%", players:"750", hot:false, isNew:false, url:"https://ubg98.github.io/Paper-io-2/" }
];
